# Generated by Django 3.1.7 on 2021-04-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210418_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trailer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Трейлер'),
        ),
    ]
