# Generated by Django 3.1.7 on 2021-04-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021, verbose_name='Год выхода'),
        ),
    ]
