# Generated by Django 3.1.7 on 2021-04-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20210425_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.CharField(default=123321, max_length=30, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
