# Generated by Django 3.1.7 on 2021-04-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.CharField(max_length=150, verbose_name='Имя пользователя'),
        ),
    ]
